### ISSUE TITLE
GioUnix-2.0?

### ISSUE THREAD

**Issue by gkoz** [gi-rust/gir#1]
Is there a reason the `gio-unix` definitions have to be in `Gio-2.0.gir`?

**Comment by mzabaluev** [comment]
The GIR files here are intentionally built like upstream (I use a fork of glib with small annotation fixes which are all pending review in GNOME Bugzilla), and the upstream has [not settled on the issue](https://bugzilla.gnome.org/show_bug.cgi?id=584936).

My current idea is to make `#[cfg(...)]` sections configurable in the crate template, where symbols will be selected by grep patterns in the same way as is done for suppression now. Then basically anything matching `*_unix_*` in the C symbol will end up in a `#[cfg(unix)] extern` block. I may do one extra step and put them in a module, with a `pub use` re-exporting at the crate level. Then people who care could import from `gio_2_0_sys::unix` to demarcate that the functions are Unix-specific. However that would be redundant for everything except `g_desktop_app_info*`.

**Comment by gkoz** [comment]
Thanks for digging this up. The split doesn't seem likely then. I'll probably have to start with suppressing all of non-portable stuff.
